Repository depromeet/InsightOut-Server, pull requests merged in 2023-05, with the labels that each got.

#17 Feature/PID-43 EB 배포 Script 설정
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
  Dockerrun.aws.json
  package.json
  src/apps/server/app.controller.ts
  src/apps/server/app.module.ts
  src/apps/server/main.ts
Labels: ☁️ AWS

#15 [Feature] signin 처리 및 토큰 발급 구현 추가
  package.json
  src/apps/server/auth/auth.controller.ts
  src/apps/server/auth/auth.module.ts
  src/apps/server/auth/auth.service.ts
  src/apps/server/auth/types/jwt-tokwn.type.ts
  src/apps/server/consts/jwt.const.ts
  src/apps/server/consts/time.const.ts
  src/apps/server/guards/jwt-auth.guard.ts
  src/apps/server/guards/jwt-refresh.guard.ts
  src/apps/server/guards/signin-request-body.interface.ts
  src/apps/server/guards/signin.guard.ts
  src/apps/server/guards/strategies/jwt-refresh.strategy.ts
  src/apps/server/guards/strategies/jwt.strategy.ts
  src/apps/server/main.ts
  src/enums/token.enum.ts
  src/modules/cache/redis/redis.service.ts
  src/modules/database/prisma.service.ts
  src/modules/database/repositories/user-info.repository.ts
  src/modules/database/repositories/user.repository.ts
  src/modules/database/schema.prisma
  yarn.lock
Labels: ⚡️ feature, 🗝️ auth

#25 dev 브랜치에 푸시될 때만 deploy.yml 실행되게 변경
  .github/workflows/deploy.yml
Labels: bug

#34 [Feature] 자기소개서 entity 작성
  src/apps/server/auth/auth.service.ts
  src/apps/server/guards/strategies/jwt.strategy.ts
  src/modules/database/schema.prisma
Labels: ⚡️ feature, 💽 database, ✨ new

#38 [Feature] 추상 레포지터리 설정 및 응답 엔티티 추가, 테스트용 액세스 토큰 발급 api 추가, 자기소개서 조회 api 추가
  src/apps/server/app.module.ts
  src/apps/server/auth/auth.module.ts
  src/apps/server/resumes/resumes.controller.ts
  src/apps/server/resumes/resumes.module.ts
  src/apps/server/resumes/resumes.service.ts
  src/apps/server/test/test.controller.ts
  src/apps/server/test/test.module.ts
  src/apps/server/test/test.service.ts
  src/libs/utils/respone.entity.ts
  src/modules/database/repositories/abstract.repository.ts
  src/modules/database/repositories/resume.repository.ts
Labels: ⚡️ feature, ✨ new, 🔥 enhancement

#41 [Fix] token 발급 방식에서의 오류 수정, 테스트 refresh 토큰 발급 추가
  src/apps/server/auth/auth.service.ts
  src/apps/server/test/test.controller.ts
  src/apps/server/test/test.module.ts
  src/apps/server/test/test.service.ts
Labels: bug, 🗝️ auth

#43 Feature/pid 27 - 경험 정보 생성 API
  .eslintrc.js
  .prettierrc
  package.json
  src/apps/server/app.module.ts
  src/apps/server/auth/auth.controller.ts
  src/apps/server/auth/auth.module.ts
  src/apps/server/auth/auth.service.ts
  src/apps/server/common/consts/jwt.const.ts
  src/apps/server/common/consts/time.const.ts
  src/apps/server/common/decorators/request/user.decorator.ts
  src/apps/server/common/decorators/returnValueToDto.ts
  src/apps/server/common/decorators/router/route-table.decorator.ts
  src/apps/server/common/decorators/router/route.decorator.ts
  src/apps/server/common/exceptions/base.exception.ts
  src/apps/server/common/exceptions/exception.type.ts
  src/apps/server/common/exceptions/unknown.exception.ts
  src/apps/server/common/exceptions/validation.exception.ts
  src/apps/server/common/filters/custom-exception.filter.ts
  src/apps/server/common/guards/jwt-auth.guard.ts
  src/apps/server/common/guards/jwt-refresh.guard.ts
  src/apps/server/common/guards/signin-request-body.interface.ts
  src/apps/server/common/guards/signin.guard.ts
  src/apps/server/common/guards/strategies/jwt-refresh.strategy.ts
  src/apps/server/common/guards/strategies/jwt.strategy.ts
  src/apps/server/common/interceptors/log.interceptor.ts
  src/apps/server/experience/dto/experience.dto.ts
  src/apps/server/experience/dto/req/createExperienceInfo.dto.ts
  src/apps/server/experience/dto/res/createExperienceInfo.res.dto.ts
  src/apps/server/experience/experience.controller.ts
  src/apps/server/experience/experience.module.ts
  src/apps/server/experience/experience.service.ts
  src/apps/server/experience/interface/experience-repository.interface.ts
  src/apps/server/experience/provider/experience.provider.ts
  src/apps/server/experience/provider/injectionToken.ts
  src/apps/server/main.ts
  src/apps/server/resumes/resumes.controller.ts
  src/apps/server/test/test.controller.ts
  src/apps/server/test/test.service.ts
  src/enums/method.enum.ts
  src/modules/database/repositories/experience-info.repository.ts
  src/modules/database/repositories/experience-transaction.repository.ts
  src/modules/database/repositories/experience.repository.ts
  src/modules/database/schema.prisma
  src/modules/slack/slack.service.ts
Labels: ⚡️ feature, 💽 database

#46 Feature/pid 44 - 경험 분해 조회 API
  package.json
  src/apps/server/common/consts/experience-attribute.const.ts
  src/apps/server/experience/dto/experience-select.dto.ts
  src/apps/server/experience/dto/experience.dto.ts
  src/apps/server/experience/dto/req/createExperienceInfo.dto.ts
  src/apps/server/experience/dto/req/experienceIdParam.dto.ts
  src/apps/server/experience/dto/res/createExperienceInfo.res.dto.ts
  src/apps/server/experience/dto/res/getExperience.res.dto.ts
  src/apps/server/experience/experience.controller.ts
  src/apps/server/experience/experience.service.ts
  src/apps/server/experience/interface/experience-repository.interface.ts
  src/apps/server/experience/interface/experience-select.interface.ts
  src/apps/server/main.ts
  src/enums/method.enum.ts
  src/modules/database/repositories/experience-transaction.repository.ts
  src/modules/database/repositories/experience.repository.ts
  src/modules/database/schema.prisma
Labels: ⚡️ feature, 💽 database

#47 [Feature] 맞춤법 검사기 추가
  package.json
  src/apps/server/auth/auth.service.ts
  src/apps/server/common/guards/jwt-auth.guard.ts
  src/apps/server/main.ts
  src/apps/server/resumes/dtos/post-spell-check-request.body.dto.ts
  src/apps/server/resumes/resumes.controller.ts
  src/apps/server/resumes/resumes.module.ts
  src/apps/server/resumes/resumes.service.ts
  src/libs/utils/hanspell.function.ts
  src/modules/api/api.service.ts
  src/modules/api/api.type.ts
  src/modules/database/prisma.service.ts
  yarn.lock
Labels: ⚡️ feature, ✨ new

#49 [Feature] 랜덤 닉네임 생성 길이를 5로 수정 + 자기소개서 추가 API
  src/apps/server/resumes/dtos/post-resume.dto.ts
  src/apps/server/resumes/resumes.controller.ts
  src/apps/server/resumes/resumes.service.ts
  src/modules/api/api.service.ts
  src/modules/database/schema.prisma
Labels: 🗝️ auth

#54 [Feature] 자기소개서 문항 수정 API
  src/apps/server/app.module.ts
  src/apps/server/resumes/controllers/question.controller.ts
  src/apps/server/resumes/dtos/patch-question-request.dto.ts
  src/apps/server/resumes/dtos/post-question.dto.ts
  src/apps/server/resumes/services/question.service.ts
  src/modules/database/schema.prisma
Labels: ⚡️ feature, ✨ new

#55 [Feature] 자기소개서 폴더 수정 API
  src/apps/server/resumes/dtos/patch-resume.dto.ts
  src/apps/server/resumes/resumes.controller.ts
  src/apps/server/resumes/resumes.service.ts
Labels: ⚡️ feature, ✨ new

#57 [Feature] #56 자기소개서 폴더 삭제 API
  src/apps/server/resumes/resumes.controller.ts
  src/apps/server/resumes/resumes.service.ts
  src/modules/database/schema.prisma
Labels: ⚡️ feature, ✨ new

#59 [Feature] #58 자기소개서 문항 삭제 API
  src/apps/server/resumes/controllers/question.controller.ts
  src/apps/server/resumes/dtos/post-question.dto.ts
  src/apps/server/resumes/services/question.service.ts
Labels: ⚡️ feature, ✨ new

#61 [Feature] 자기소개서 모아보기 sorting 추가 및 Response DTO 연결
  src/apps/server/common/dtos/get-filter-sort-query.dto.ts
  src/apps/server/common/enums/sort.enum.ts
  src/apps/server/resumes/controllers/resumes.controller.ts
  src/apps/server/resumes/dtos/get-resume.dto.ts
  src/apps/server/resumes/resumes.controller.ts
  src/apps/server/resumes/resumes.service.ts
  src/apps/server/resumes/services/resumes.service.ts
Labels: ⚡️ feature, 🔥 enhancement, [API] Resume

#64 [Feature] module을 libs폴더로 이동
  src/apps/server/app.module.ts
  src/apps/server/auth/auth.module.ts
  src/apps/server/auth/auth.service.ts
  src/apps/server/common/filters/custom-exception.filter.ts
  src/apps/server/common/guards/strategies/jwt-refresh.strategy.ts
  src/apps/server/common/guards/strategies/jwt.strategy.ts
  src/apps/server/common/interceptors/log.interceptor.ts
  src/apps/server/experience/experience.controller.ts
  src/apps/server/experience/experience.service.ts
  src/apps/server/experience/interface/experience-repository.interface.ts
  src/apps/server/experience/provider/experience.provider.ts
  src/apps/server/experience/provider/injectionToken.ts
  src/apps/server/main.ts
  src/apps/server/resumes/resume.provider.ts
  src/apps/server/resumes/resumes.module.ts
  src/apps/server/resumes/services/question.service.ts
  src/apps/server/resumes/services/resumes.service.ts
  src/apps/server/test/test.module.ts
  src/apps/server/test/test.service.ts
  src/libs/modules/api/api.module.ts
  src/libs/modules/api/api.service.ts
  src/libs/modules/api/api.type.ts
  src/libs/modules/cache/redis/redis.factory.ts
  src/libs/modules/cache/redis/redis.module.ts
  src/libs/modules/cache/redis/redis.service.ts
  src/libs/modules/database/database.module.ts
  src/libs/modules/database/migrations/20230508121826_test/migration.sql
  src/libs/modules/database/migrations/migration_lock.toml
  src/libs/modules/database/prisma.service.ts
  src/libs/modules/database/repositories/abstract.repository.ts
  src/libs/modules/database/repositories/experience-info.repository.ts
  src/libs/modules/database/repositories/experience-transaction.repository.ts
  src/libs/modules/database/repositories/experience.repository.ts
  src/libs/modules/database/repositories/question.repository.ts
  src/libs/modules/database/repositories/resume.repository.ts
  src/libs/modules/database/repositories/user-info.repository.ts
  src/libs/modules/database/repositories/user.repository.ts
  src/libs/modules/database/schema.prisma
  src/libs/modules/env/env.enum.ts
  src/libs/modules/env/env.module.ts
  src/libs/modules/env/env.service.ts
  src/libs/modules/log/log.module.ts
  src/libs/modules/log/log.service.ts
  src/libs/modules/slack/slack.enum.ts
  src/libs/modules/slack/slack.module.ts
  src/libs/modules/slack/slack.service.ts
Labels: ♻️ refactor

#66 [Feature] 구글 로그인을 Firebase 방식으로 변경
  .github/workflows/deploy.yml
  package.json
  src/apps/server/auth/auth.module.ts
  src/apps/server/auth/auth.service.ts
  src/apps/server/common/guards/signin.guard.ts
  src/apps/server/experience/dto/experience.dto.ts
  src/libs/modules/database/repositories/experience-transaction.repository.ts
  src/libs/modules/database/schema.prisma
  src/modules/firebase/firebase.module.ts
  src/modules/firebase/firebase.service.ts
  yarn.lock
Labels: 🗝️ auth, 🔥 enhancement

#68 [Feature] 파이어베이스 로그인 PR 재적용
  src/apps/server/auth/auth.module.ts
  src/apps/server/common/guards/signin.guard.ts
  src/apps/server/experience/interface/experience-repository.interface.ts
  src/libs/modules/database/repositories/experience-transaction.repository.ts
  src/libs/modules/database/repositories/experience.repository.ts
  src/libs/modules/firebase/firebase.module.ts
  src/libs/modules/firebase/firebase.service.ts
Labels: bug, 🔥 enhancement

#69 Refactor/#67/code convention
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  src/apps/server/app.module.ts
  src/apps/server/common/consts/date-validation.const.ts
  src/apps/server/common/consts/experience-attribute.const.ts
  src/apps/server/common/decorators/validation/isOptionalNumber.decorator.ts
  src/apps/server/common/decorators/validation/isOptionalString.decorator.ts
  src/apps/server/experience/dto/experience-select.dto.ts
  src/apps/server/experience/dto/experience.dto.ts
  src/apps/server/experience/experience.service.ts
  src/apps/server/experience/provider/experience.provider.ts
  src/apps/server/experiences/dto/experience.dto.ts
  src/apps/server/experiences/dto/req/createExperienceInfo.dto.ts
  src/apps/server/experiences/dto/req/experienceIdParam.dto.ts
  src/apps/server/experiences/dto/res/createExperienceInfo.res.dto.ts
  src/apps/server/experiences/dto/res/getExperience.res.dto.ts
  src/apps/server/experiences/experience.controller.ts
  src/apps/server/experiences/experience.module.ts
  src/apps/server/experiences/experience.service.ts
  src/apps/server/experiences/interface/experience-repository.interface.ts
  src/apps/server/experiences/interface/experience-select.interface.ts
  src/apps/server/experiences/provider/experience.provider.ts
  src/libs/modules/database/repositories/experience-transaction.repository.ts
  src/libs/modules/database/repositories/experience.repository.ts
Labels: ♻️ refactor

#72 Feature/#70/pid 70/modify get experience flow
  src/apps/server/experiences/dto/experience.dto.ts
  src/apps/server/experiences/dto/req/createExperienceInfo.dto.ts
  src/apps/server/experiences/dto/req/experienceIdParam.dto.ts
  src/apps/server/experiences/dto/res/createExperienceInfo.res.dto.ts
  src/apps/server/experiences/dto/res/getExperience.res.dto.ts
  src/apps/server/experiences/experience.controller.ts
  src/apps/server/experiences/experience.service.ts
  src/apps/server/experiences/interface/experience-repository.interface.ts
  src/libs/modules/database/repositories/experience.repository.ts
Labels: ♻️ refactor, [API] Experience

#73 [Feature] 컬럼 속성 업데이트
  src/apps/server/main.ts
  src/libs/modules/database/schema.prisma
  src/libs/utils/date.ts
  tsconfig.json
Labels: 💽 database, 🔥 enhancement
